export const message = {
  // 1xx Informational
  continue: "Continue",
  switchingProtocols: "Switching Protocols",
  processing: "Processing request",
  earlyHints: "Early hints available",

  // 2xx Success
  ok: "Success",
  created: "Created successfully",
  accepted: "Request accepted",
  nonAuthoritativeInformation: "Non-authoritative information",
  noContent: "No content",
  resetContent: "Reset content",
  partialContent: "Partial content",

  // 3xx Redirection
  multipleChoices: "Multiple redirect options available",
  movedPermanently: "Resource moved permanently",
  found: "Resource found elsewhere",
  seeOther: "See other resource",
  notModified: "Resource not modified",
  useProxy: "Use proxy to access resource",
  temporaryRedirect: "Resource temporarily moved",
  permanentRedirect: "Resource permanently moved",

  // 4xx Client Error
  badRequest: "Invalid request",
  unauthorized: "Authentication required",
  paymentRequired: "Payment required",
  forbidden: "You don't have permission to access this resource",
  notFound: "Resource not found",
  methodNotAllowed: "Method not allowed for this resource",
  notAcceptable: "Requested format not available",
  proxyAuthenticationRequired: "Proxy authentication required",
  requestTimeout: "Request timed out",
  conflict: "Resource conflict detected",
  gone: "Resource no longer available",
  lengthRequired: "Content length header is required",
  preconditionFailed: "Request precondition failed",
  payloadTooLarge: "Request payload exceeds size limit",
  uriTooLong: "Request URI exceeds length limit",
  unsupportedMediaType: "Unsupported media type",
  rangeNotSatisfiable: "Requested range is not available",
  expectationFailed: "Request expectation could not be met",
  imATeapot: "I'm a teapot",
  unprocessableEntity: "Unable to process request entity",
  tooEarly: "Request sent too early, retry later",
  upgradeRequired: "Protocol upgrade required",
  preconditionRequired: "Precondition header is required",
  tooManyRequests: "Too many requests, please slow down",
  requestHeaderFieldsTooLarge: "Request headers exceed size limit",
  unavailableForLegalReasons: "Resource unavailable for legal reasons",

  // 5xx Server Error
  internalServerError: "Something went wrong on our end",
  notImplemented: "Feature not yet implemented",
  badGateway: "Bad gateway response from upstream",
  serviceUnavailable: "Service temporarily unavailable, try again later",
  gatewayTimeout: "Upstream server timed out",
  httpVersionNotSupported: "HTTP version not supported by server",
  insufficientStorage: "Server has insufficient storage",
  loopDetected: "Infinite request loop detected",
  notExtended: "Server cannot fulfill extended request",
  networkAuthenticationRequired: "Network authentication required",
} as const;
